model:
  name: Padim
  backbone: mcunet-in3
  layers:
  - 3
  - 6
  - 9
  optimizer: null
  loss_function: null
dataset:
  name: adnet
  path: /mnt/disk1/ruslan_nuriev/adnet
  img_size:
  - 256
  - 256
  mask_size:
  - 256
  - 256
  transforms: null
train:
  batch_size: 32
  epochs: 1
  early_stop: null
  device: cuda:2
  logging: true
  aggregated: true
