model:
  name: PatchCore
  backbone: resnet18
  layers:
  - layer2
  - layer3
  optimizer: null
  loss_function: null
dataset:
  name: adnet
  path: /mnt/disk2/VAD_DATASETS/Medical/Medical
  img_size:
  - 256
  - 256
  mask_size:
  - 256
  - 256
  transforms: null
train:
  batch_size: 32
  epochs: 3
  early_stop:
    patience: 3
    min_delta: 0.02
    metric: img_f1
  device: cuda:2
  logging: true
  aggregated: true
